# fly.toml app configuration file generated for superfy-sticky-add-to-cart on 2025-07-17T09:17:06+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'superfy-sticky-add-to-cart'
primary_region = 'otp'

[build]

[env]
  PORT = '3000'
  SCOPES = 'write_products'
  SHOPIFY_API_KEY = '038389d96f31e6eb643501cd0e5ed6d'
  SHOPIFY_APP_URL = 'superfy-sticky-add-to-cart'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
