services:
  - type: web
    name: superfy-sticky-bar
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build
      npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: superfy-sticky-bar-db
          property: connectionString
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_SCOPES
        sync: false
      - key: SHOPIFY_APP_URL
        sync: false
    autoDeploy: true
    
databases:
  - name: superfy-sticky-bar-db
    plan: free
    ipAllowList: [] 