# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4f015ff20f4e9ae4f092208276e2efef"
name = "superfy-sticky-add-to-cart"
handle = "superfy-sticky-add-to-cart"
application_url = "https://setup-matched-blah-repository.trycloudflare.com"
embedded = true
dev_store = "sticky-add-to-cart-develop.myshopify.com"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://setup-matched-blah-repository.trycloudflare.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://setup-matched-blah-repository.trycloudflare.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_app_proxy"

[auth]
redirect_urls = ["https://setup-matched-blah-repository.trycloudflare.com/auth/callback", "https://setup-matched-blah-repository.trycloudflare.com/auth/shopify/callback", "https://setup-matched-blah-repository.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://setup-matched-blah-repository.trycloudflare.com"
prefix = "apps"
subpath = "proxy"
