# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e14eab145dbfee056d2e38e3e2ab9d73"
name = "sticky-add-to-cart-develop"
handle = "sticky-add-to-cart-develop"
application_url = "https://licence-fda-practices-st.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_app_proxy"

[auth]
redirect_urls = ["https://licence-fda-practices-st.trycloudflare.com/auth/callback", "https://licence-fda-practices-st.trycloudflare.com/auth/shopify/callback", "https://licence-fda-practices-st.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[app_proxy]
url = "https://licence-fda-practices-st.trycloudflare.com"
prefix = "apps"
subpath = "proxy"
